# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
                ('cpu', models.BigIntegerField(default=0, verbose_name='CPU')),
                ('memory', models.BigIntegerField(default=0, verbose_name='\u5185\u5b58')),
                ('io_in', models.BigIntegerField(default=0, verbose_name='io\u5199\u5165')),
                ('io_out', models.BigIntegerField(default=0, verbose_name='io\u8bfb\u5165')),
            ],
            options={
                'verbose_name_plural': '\u7cfb\u7edf\u4fe1\u606f',
            },
        ),
    ]
