# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboad',
            name='net',
            field=models.IntegerField(default=0, verbose_name='\u7f51\u7edc\u901f\u5ea6'),
        ),
        migrations.AlterField(
            model_name='dashboad',
            name='cpu',
            field=models.FloatField(default=0.0, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='dashboad',
            name='memory',
            field=models.FloatField(default=0, verbose_name='\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='dashboad',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
